### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Tmplt** [Tmplt/nixos-config#1]
The configurations for temeraire and praecursoris and hella messy, I need to clean them up. Follow [this repos](https://github.com/tazjin/nixos-config) footsteps.

What I need to do:
- [x] Properly isolate PCI-passthrough settings into its own module
- [x] Move common Nix expressions to `configuration.nix`
- [x] Setup Wifi network access in Nix, hiding secrets in encrypted file
- [x] Move common nixops expressions so some common file
- [ ] Consider how dotfiles can be integrated
- [x] store `task`-related files under `secrets/`
- [x] fix building of `pbpst`

PCI-passthrough specific:
- [x] Add an option to specify a list of devices to end up in `cgroup_device_acl`
- [ ] Fix so that `libvirt-guests.service` doesn't automatically resume guests if host shutdown.
- [x] Do the same, but for devices that should be assigned to the `vfio-pci` driver.
- [x] Keep `vidya.xml` in version control in this repo.
- [x] Run user `libvirt-import.service` upon system rebuild.

More to come...

**Comment by Tmplt** [comment]
The best outcome would if we could store `vidya.xml` as-in in repo, and just do `virsh define <path-to-xml> --validate` when we build the system. Is this possible?

**Comment by Tmplt** [comment]
As for running `libvirt-import.service` on system rebuild. We can simply check hostname and do that when #7 is resolved.

**Comment by Tmplt** [comment]
Mostly finished with all points. Closing in favor of future dedicated issues.
